pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-credentials', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                    git branch: 'main', credentialsId: 'github-credentials', url: 'https://github.com/chinazagideon/alx-backend-python.git'
                }
            }
        }
          stage('Build and Test') {
            steps {
                sh 'pip install -r messaging_app/requirements.txt'
                sh 'pytest --junitxml=reports/tests.xml'
            }
        }
    }
}
