pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/chinazagideon/alx-backend-python/tree/main/messaging_app'
            }
        }
          stage('Build and Test') {
            steps {
                sh 'pip install -r requirements.txt'
                sh 'pytest --junitxml=reports/tests.xml'
            }
        }
    }
}
